#!/bin/bash

## PosixAccount & PosixGroup Add for samba4 
## Tested On CentOS/RHEL
## Author :- Rahul Patil

# Change Samba4 binary location if needed 
export PATH=$PATH:/usr/local/samba/bin/

# Your DC Info
DN='DC=linuxian,DC=loc'
Host='localhost'
pass='admin@123'		# leave blank if you want interactive password prompt 

## Check 1# ldapmodify installed or not 
[[ -x $(command -v ldapmodify) ]] || { echo "Please Install Openldap-clients"; exit 1; };

# temp data
ldiftmp=$(mktemp)

show_help(){
	cat <<-_EOF
	Usage $0 OPTION..
			-u  <username>
			-g  <groupname>
		
	_EOF

}

modify(){
	[[ -z $pass ]] && 
	read -p  "Enter Administrator Password to Apply the changes" pass
	ldapmodify -h $Host -D CN=Administrator,CN=Users,$DN -f $ldiftmp -w $pass 
	
}

search(){
	[[ $# == 1 ]] && read -n1 -p "Do you want to see details (y/n)? " 
	[[ $REPLY =~ [yY] ]] && 
	/usr/local/samba/bin/ldbsearch -U Administrator%${pass} -H ldap://$Host cn=$1
}


s4group(){
	## Check Group exists or not 
	if ! samba-tool group list | grep -wq $1; then 
		## Add user using samba-tool 
		samba-tool group add $1
	fi

	gid=$(wbinfo --group-info=$1 | cut -d":" -f 3)
	
	if ! search $1 test | grep -q posixGroup; then
	
		cat <<-_EOF > $ldiftmp
		dn: cn=$1,cn=Users,$DN
		changetype: modify
		add:objectclass
		objectclass: posixGroup
		-
		add: gidnumber
		gidnumber: $gid
		_EOF
		modify
		search $1
	else
		echo "Group: $1 Already have PosixGroup Details"
		echo "exit"
		exit 1 
	fi 
	
}

s4user(){
	## Check Group exists or not 
	if ! samba-tool user list | grep -wq $1; then 
		## Add user using samba-tool 
		echo "Set Password for User $1"
		samba-tool user add $1
	fi

	uid=$(wbinfo --user-info=$1 | cut -d":" -f 3)
	HomeDir=$(wbinfo --user-info=$1 | cut -d":" -f 6)
	checkgid=$(wbinfo --user-info=$1 | cut -d":" -f 4)
	
	if [[  $checkgid < 3000000 ]]; then
		echo "It's seems Group is not define for this user"
		read -p "Do you want to specify group (y/n)? " 
		if [[ $REPLY =~ [Yy] ]]; then
			read -p "Enter Group Name: " newgrp
			gid=$(wbinfo --group-info=$newgrp | cut -d':' -f 3)
		fi 
	fi 
	
	if ! search $1 test | grep -q posixAccount; then
		cat <<-_EOF > $ldiftmp
		dn: cn=$1,cn=Users,$DN
		changetype: modify
		add:objectclass
		objectclass: posixAccount
		-
		add: uidNumber
		uidNumber: $uid
		-
		add: gidnumber
		gidnumber: $gid
		-
		add: unixHomeDirectory
		unixHomeDirectory: $HomeDir
		-
		add: loginShell
		loginShell: /bin/bash
		_EOF
		modify
		search $1
	else 
		echo "User: $1 already have PosixAccount Detials"
		echo "exit"
		exit 1
	fi
}

[[ $# < 2 ]] && { show_help; exit 1; };

case $1 in 
	-u|-U) s4user $2  	;;
	-g|-G) s4group $2 	;;
	*)	show_help	;;
esac

[[ -f $ldiftmp ]] && rm $ldiftmp
